name: todo_list
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  google_fonts: ^6.2.1
  flutter_signin_button: ^2.0.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  validatorless: ^1.2.3
  flutter_overlay_loader: ^2.0.0
  synchronized: ^3.1.0+1
  google_sign_in: ^6.2.1
  date_picker_timeline: ^1.2.6
  intl: ^0.19.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/